### ISSUE TITLE
Memory corruption with v6.0

### ISSUE THREAD

**Issue by lummax** [lonsing/depqbf#10]
With `depbf` 6.0 I get a corrupted double-linked list with [problem.qdimacs](
https://gist.github.com/lummax/a4d26785f782b5ac42c81438f40de641). It worked on version 5.01.

```
➤ depqbf --version
DepQBF 5.01
Copyright 2010, 2011, 2012, 2013, 2014, 2015, 2016 Florian Lonsing,
  Johannes Kepler University, Linz, Austria and
  Vienna University of Technology, Vienna, Austria.
Copyright 2012 Aina Niemetz, Johannes Kepler University, Linz, Austria.
This is free software; see COPYING for copying conditions.
There is NO WARRANTY, to the extent permitted by law.
➤ depqbf problem.dimacs
SAT
```

```
➤ depqbf --version
DepQBF 6.0
Copyright 2013, 2014, 2015, 2016, 2017 Florian Lonsing,
  Vienna University of Technology, Vienna, Austria.
Copyright 2010, 2011, 2012 Florian Lonsing,
  Johannes Kepler University, Linz, Austria.
Copyright 2012 Aina Niemetz,
  Johannes Kepler University, Linz, Austria.
This is free software; see COPYING for copying conditions.
There is NO WARRANTY, to the extent permitted by law.
➤ depqbf problem.dimacs
*** Error in `depqbf': corrupted double-linked list: 0x000000000143ecd0 ***
======= Backtrace: =========
[0x44a588]
[0x44fb69]
[0x45214d]
[0x4539d4]
[0x426cc2]
[0x42a5f1]
[0x42dffc]
[0x424e55]
[0x41a5a0]
[0x40166c]
[0x43bd82]
[0x43bffe]
[0x400c5a]
======= Memory map: ========
00400000-004fb000 r-xp 00000000 fe:00 2650631                            /nix/store/2z54agdlr579q12f7mvab8yq96biazdw-depqbf-6.0/bin/depqbf
006fb000-00701000 rw-p 000fb000 fe:00 2650631                            /nix/store/2z54agdlr579q12f7mvab8yq96biazdw-depqbf-6.0/bin/depqbf
00701000-00703000 rw-p 00000000 00:00 0 
011fe000-016c3000 rw-p 00000000 00:00 0                                  [heap]
7f56c4000000-7f56c4024000 rw-p 00000000 00:00 0 
7f56c4024000-7f56c8000000 ---p 00000000 00:00 0 
7f56cb940000-7f56cb9c2000 rw-p 00000000 00:00 0 
7ffdc3474000-7ffdc3497000 rw-p 00000000 00:00 0                          [stack]
7ffdc356a000-7ffdc356c000 r--p 00000000 00:00 0                          [vvar]
7ffdc356c000-7ffdc356e000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
[1]    16739 abort      depqbf problem.dimacs
```

The `gdb` backtrace shows an error in `bloqqer`, but that may be due to invalid use? Unfortunately I've got no time at my hands to dig deeper.

```
#0  0x00000000004416b4 in raise ()
#1  0x0000000000441b5a in abort ()
#2  0x000000000044a58d in __libc_message ()
#3  0x000000000044fb69 in malloc_printerr ()
#4  0x000000000045214d in _int_malloc ()
#5  0x00000000004539d4 in malloc ()
#6  0x0000000000426cc2 in clause_stack_push ()
#7  0x000000000042a5f1 in eqres.part ()
#8  0x000000000042dffc in bloqqer_preprocess ()
#9  0x0000000000424e55 in dynamic_bloqqer_test ()
#10 0x000000000041a5a0 in qdpll_sat ()
#11 0x000000000040166c in qdpll_main ()
#12 0x000000000043bd82 in generic_start_main ()
#13 0x000000000043bffe in __libc_start_main ()
#14 0x0000000000400c5a in _start ()
```

**Comment by lonsing** [comment]
Hi,
thank you very much for pointing this out! I have published a new release (6.01) to fix the problem.
Best regards,
Florian
